python3 GenerateRecedingHorizonResults.py antfarm_firstLevel_right_start previous NLP

python3 GenerateRecedingHorizonResults.py antfarm_firstLevel_right_start previous CoM

python3 GenerateRecedingHorizonResults.py antfarm_firstLevel_right_start random NLP

python3 GenerateRecedingHorizonResults.py antfarm_firstLevel_right_start random CoM
