python3 GenerateRecedingHorizonResults.py darpa_like_left_first previous NLP

python3 GenerateRecedingHorizonResults.py darpa_like_left_first previous CoM

python3 GenerateRecedingHorizonResults.py darpa_like_left_first random NLP

python3 GenerateRecedingHorizonResults.py darpa_like_left_first random CoM