python3 GenerateRecedingHorizonResults.py flat random NLP

python3 GenerateRecedingHorizonResults.py antfarm_firstLevel_left_start random NLP

python3 GenerateRecedingHorizonResults.py up_and_down_left_first random NLP

python3 GenerateRecedingHorizonResults.py darpa_like_left_first random NLP
