python3 GenerateRecedingHorizonResults.py up_and_down_left_first previous NLP

python3 GenerateRecedingHorizonResults.py up_and_down_left_first previous CoM

python3 GenerateRecedingHorizonResults.py up_and_down_left_first random NLP

python3 GenerateRecedingHorizonResults.py up_and_down_left_first random CoM