python3 GenerateRecedingHorizonResults.py up_and_down_right_first previous NLP

python3 GenerateRecedingHorizonResults.py up_and_down_right_first previous CoM

python3 GenerateRecedingHorizonResults.py up_and_down_right_first random NLP

python3 GenerateRecedingHorizonResults.py up_and_down_right_first random CoM